---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Meh ...


But, maybe we can marching squares - here's a rough stab at the codes for the cases: 

```{r marching, eval = FALSE}
library(raster)

r <- raster(volcano)

v <- 120
#contour(r, level = v)

mask <- r >= v
plot(mask)
twobytwo <- function(x, row = 1) {
 ind <-  matrix(c(1, 2) + c(0, 0, rep(ncol(r), 2)), nrow = 4, ncol = ncol(r) - 1) + 
    cellFromRow(r, 1) - 1
 ind + ncol(r) * (row-1)
}
plot(mask)
codes <- vector("list", nrow(r)-1)
pak <- function(x) {
  as.integer(packBits(as.integer(c(x, 0, 0, 0, 0)), type = "raw"))
}
options(warn = -1)
for (row in seq_len(nrow(mask)-1)) {
  codes[[row]] <- apply(matrix(extract(mask, c(twobytwo(r, row))), nrow = 4), 2, pak)
}
 

lookup_table <- function(code, coord, res) {
  ## build the segment on the coord with the given resolution
  ## case 1
  xy1 <- c(res[1]/2, 0)
  xy2 <- c(0, -res[2]/2)
  
  ## case2
  xy1 <- c(0, -res[2]/2)
  xy2 <- c(0, res[1]/2)
  
  ## etc, figure out cunning lookup
  coords <- rbind(coord, coord)
  
} 

```

## Installation

You can install contourPolys from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("hypertidy/contourPolys")
```


This is a basic example which shows you how to solve a common problem:

```{r example, eval = FALSE}

library(raster)
r <- aggregate(raster(volcano), fact = 2, fun = median) %/% 20
r <- tabularaster:::set_indextent(r)
plot(r, asp = "")
#val <- cellStats(r, min)
#r <- extend(r, 1, value = val-1)

x <- list(x = xFromCol(r), y = rev(yFromRow(r)), z = t(as.matrix(flip(r, "y"))))
clevels <- sort(na.omit(unique(values(r))))
cl <- contourLines(x, levels = clevels)
bound <- as(as(extent(r), "SpatialPolygons"), "SpatialLines")@lines[[1]]@Lines

resx <- res(r)[1]
resy <- res(r)[2]

## note order here to trace around correctly
## and has to be centres to align to contourLines' assumption
xcentres <-  xFromCol(r) ##seq(xmin(r), xmax(r), length.out = ncol(r) + 1)
ycentres <-  rev(yFromRow(r)) #seq(ymin(r), ymax(r), length.out = nrow(r) + 1)
boundary_coords <- rbind(
                    cbind(xmin(r), ycentres), 
                    cbind(xcentres, ymax(r)), 
                    cbind( xmax(r), rev(ycentres)), 
                    cbind(rev(xcentres), ymin(r))
)
nearest_point <- function(coords, pt) {
  distances <- sqrt((coords[,1] - pt[1])^2 + 
                      (coords[,2] - pt[2])^2)
  coords[which.min(distances), , drop = FALSE]
  
}
mesh_lines <- vector("list", length(cl))
 
for (i in seq_along(cl)) {
  xxs <- cl[[i]]$x
  yys <- cl[[i]]$y
  npts <- length(xxs)
  bounded <- 
    abs(xxs[1] - xxs[npts]) < sqrt(.Machine$double.eps) &&
    abs(yys[1] - yys[npts]) < sqrt(.Machine$double.eps)
  ## create polygon if bounded
  if (bounded) {
    mesh_lines[[i]] <- cbind(xxs, yys)
  } else {
    ## otherwise insert extra coordinates to nearest side
    pt1 <- nearest_point(boundary_coords, cbind(xxs[1], yys[1]))
    pt2 <- nearest_point(boundary_coords, cbind(xxs[npts], yys[npts]))
    mesh_lines[[i]] <- rbind(pt1, cbind(xxs, yys), pt2)
   }
}

plot(r, asp = "")
lapply(mesh_lines, lines)
## note this must be a single multi-line
ll <- sp::Lines(lapply(c(mesh_lines, list(boundary_coords)), sp::Line), "1")
#x <- sp::SpatialLines(lapply(seq_along(ll), function(i) sp::Lines(ll[[i]], as.character(i))))
x <- sp::SpatialLines(list(ll))

## now we have the right structures
ct <- sf::st_cast(sfdct::ct_triangulate(sf::st_as_sf(x)))
library(sf)
sp_ct <- as(ct, "Spatial")
sp_ct$id <- seq_len(nrow(sp_ct))
sp_ct$contour_level <- clevels[findInterval(extract(r, do.call(rbind, lapply(sp_ct@polygons, function(x) x@labpt))), 
             clevels)]
sp_ct$id <- NULL
ct <- rgeos::gUnionCascaded(sp_ct, sp_ct$contour_level)
plot(st_as_sf(ct))
## now merge
#library(dplyr)
st_as_sf(sp_ct) %>% group_by(contour_level) %>% mutate(geometry = st_combine(geometry))
```
