# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Filled contour
#'
#' @param x vector x coordinate
#' @param y vector x coordinate
#' @param z vector z matrix
#' @export
fcontour <- function(x, y, z, c) {
    .Call(`_contourPolys_fcontour`, x, y, z, c)
}

#' Filled contour
#'
#' @param x vector x coordinate
#' @param y vector x coordinate
#' @param z vector z matrix
#' @export
#' @examples
#' library(raster)
#'   data("topo", package = "contourPolys")
#'   levels <- c(-6000, -4000, -2000, 0, 2000, 4000)
#'   fc <- fcontour_sf(xFromCol(topo), rev(yFromRow(topo)), t(as.matrix(flip(topo, "y"))), c = levels)
#'   g <- purrr::map(fc[[1]], ~sf::st_polygon(list(.x)))
#'   ik <- unlist(fc[[2]])
#'   library(dplyr)
#'   x <- st_sf(geometry = st_sfc(g), kk = ik) %>% group_by(kk) %>% summarize() %>% st_cast("MULTIPOLYGON")
#'   ramp2 <- grDevices::colorRampPalette(c("#54A3D1", "#60B3EB", 
#'                                          "#78C8F0", "#98D1F5", "#B5DCFF", "#BDE1F0", "#CDEBFA", 
#'                                          "#D6EFFF", "#EBFAFF", "grey92", "grey94", "grey96", "white"))
#'     plot(x, col = ramp2(nrow(x)))
fcontour_sf <- function(x, y, z, c) {
    .Call(`_contourPolys_fcontour_sf`, x, y, z, c)
}

